import { useEffect, useState } from "react";
import { BarChart3, Download, FlaskConical, ShieldCheck } from "lucide-react";
import { downloadResearchEvidence, getGlobalShap, getPendingProspectivePredictions, getResearchSummary, saveEffectivenessRecord, saveProspectiveOutcome, saveUsabilitySession } from "../services/api";

type Json = Record<string, unknown>;
const inputClass = "h-11 rounded-xl border border-slate-300 bg-white px-3 text-sm dark:border-slate-700 dark:bg-slate-950";

export default function ResearchWorkspace() {
  const [summary, setSummary] = useState<Json>({});
  const [shap, setShap] = useState<{ features?: Array<{ feature: string; mean_absolute_shap: number; observations: number }>; warning?: string }>({});
  const [pending, setPending] = useState<Json[]>([]);
  const [status, setStatus] = useState("");
  const [participant, setParticipant] = useState("");
  const [ethics, setEthics] = useState("");
  const [sus, setSus] = useState<number[]>(Array(10).fill(3));
  const [predictionId, setPredictionId] = useState("");

  async function load() {
    const [summaryResult, shapResult, pendingResult] = await Promise.allSettled([
      getResearchSummary(), getGlobalShap(), getPendingProspectivePredictions(),
    ]);
    if (summaryResult.status === "fulfilled") setSummary(summaryResult.value);
    if (shapResult.status === "fulfilled") setShap(shapResult.value);
    if (pendingResult.status === "fulfilled") setPending(pendingResult.value);
    const failures = [summaryResult, shapResult, pendingResult].filter(result => result.status === "rejected");
    setStatus(failures.length ? `${failures.length} research data source${failures.length === 1 ? " is" : "s are"} currently unavailable.` : "");
  }
  useEffect(() => { void load(); }, []);
  const maxShap = Math.max(...(shap.features ?? []).map((item) => item.mean_absolute_shap), 0.0001);
  const model = (summary.model ?? {}) as Json;
  const metrics = (model.test_metrics ?? {}) as Json;
  const classifications = (summary.prediction_classifications ?? {}) as Json;
  async function run(action: () => Promise<unknown>, success: string) { try { await action(); setStatus(success); await load(); } catch (error) { setStatus(error instanceof Error ? error.message : "Action failed"); } }

  return <div className="dashboard-shell space-y-6">
    <header className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-blue-600">Restricted admin/research area</p><h1 className="mt-2 text-3xl font-extrabold">Research evidence workspace</h1><p className="mt-2 max-w-3xl text-sm text-slate-600 dark:text-slate-300">Separates model evidence and approved study records from patient care. Nothing here establishes regulatory approval or clinical effectiveness by itself.</p></div><button className="clinical-button flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-3 text-sm font-bold text-white" onClick={() => void downloadResearchEvidence()}><Download className="h-4 w-4"/>Export evidence</button></header>
    {status && <p role="status" aria-live="polite" className="rounded-xl border border-blue-200 bg-blue-50 p-3 text-sm text-blue-900">{status}</p>}
    <section aria-labelledby="study-status" className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><h2 id="study-status" className="sr-only">Study evidence status</h2>{[["Predictions", model.available ? "Available" : "Unavailable"],["Usability sessions", summary.usability_sessions ?? 0],["Prospective outcomes", summary.prospective_outcomes ?? 0],["Effectiveness records", summary.effectiveness_records ?? 0]].map(([label,value])=><article key={String(label)} className="glass-card p-5"><p className="text-xs font-bold uppercase text-slate-500">{String(label)}</p><p className="mt-2 text-2xl font-extrabold">{String(value)}</p></article>)}</section>
    <div className="grid gap-6 lg:grid-cols-2"><section className="glass-card p-6" aria-labelledby="model-evaluation-title"><h2 id="model-evaluation-title" className="text-xl font-extrabold">Model evaluation</h2><dl className="mt-4 grid grid-cols-2 gap-4 text-sm"><div><dt className="text-slate-500">Version</dt><dd className="font-bold">{String(model.model_version ?? "Unavailable")}</dd></div><div><dt className="text-slate-500">ROC-AUC</dt><dd className="font-bold">{Number(metrics.roc_auc ?? 0).toFixed(3)}</dd></div><div><dt className="text-slate-500">Sensitivity</dt><dd className="font-bold">{Number(metrics.recall_sensitivity ?? 0).toFixed(3)}</dd></div><div><dt className="text-slate-500">Specificity</dt><dd className="font-bold">{Number(metrics.specificity ?? 0).toFixed(3)}</dd></div></dl></section><section className="glass-card p-6" aria-labelledby="shadow-title"><h2 id="shadow-title" className="text-xl font-extrabold">Shadow and prospective validation</h2><dl className="mt-4 grid grid-cols-4 gap-3 text-sm">{["TP","FP","TN","FN"].map(key=><div key={key}><dt className="text-slate-500">{key}</dt><dd className="text-xl font-extrabold">{String(classifications[key] ?? 0)}</dd></div>)}</dl><p className="mt-4 text-xs text-slate-500">Live sensitivity and specificity are calculated only after future outcomes are adjudicated.</p></section></div>
    <section className="glass-card p-6" aria-labelledby="global-shap-title"><div className="flex items-center gap-3"><BarChart3 className="h-6 w-6 text-blue-600"/><h2 id="global-shap-title" className="text-xl font-extrabold">Global SHAP population analysis</h2></div><p className="mt-2 text-sm text-slate-500">Mean absolute contributions across stored prospective predictions. Longer bars influence model output more; they do not prove causation.</p><div className="mt-5 space-y-3">{(shap.features ?? []).slice(0,12).map(item=><div key={item.feature}><div className="flex justify-between text-sm"><span>{item.feature.replaceAll("_"," ")}</span><span>{item.mean_absolute_shap.toFixed(4)} · n={item.observations}</span></div><div className="mt-1 h-3 rounded-full bg-slate-100 dark:bg-slate-800" role="img" aria-label={`${item.feature} mean absolute SHAP ${item.mean_absolute_shap.toFixed(4)}`}><div className="h-full rounded-full bg-blue-600" style={{width:`${Math.max(2,item.mean_absolute_shap/maxShap*100)}%`}}/></div></div>)}{!(shap.features?.length) && <p className="text-sm">Global SHAP becomes available after shadow predictions have been stored.</p>}</div></section>
    <div className="grid gap-6 xl:grid-cols-2">
      <form className="glass-card space-y-4 p-6" onSubmit={event=>{event.preventDefault(); void run(()=>saveUsabilitySession({participant_code:participant,participant_role:"other",protocol_version:"1.0",consent_confirmed:true,ethics_reference:ethics,task_results:[],sus_responses:sus}),"Usability evidence saved with calculated SUS score.")}}><h2 className="text-xl font-extrabold">Usability and SUS collection</h2><p className="text-sm text-slate-500">Use pseudonymous participant codes only. Submit only after documented ethics and consent.</p><label className="grid gap-1 text-sm font-bold">Participant code<input className={inputClass} value={participant} onChange={e=>setParticipant(e.target.value)} required/></label><label className="grid gap-1 text-sm font-bold">Ethics/approval reference<input className={inputClass} value={ethics} onChange={e=>setEthics(e.target.value)} required/></label><fieldset><legend className="text-sm font-bold">SUS responses (1 strongly disagree – 5 strongly agree)</legend><div className="mt-2 grid grid-cols-2 gap-2 sm:grid-cols-5">{sus.map((value,index)=><label key={index} className="text-xs">Q{index+1}<select className={`${inputClass} mt-1 w-full`} value={value} onChange={e=>setSus(sus.map((item,i)=>i===index?Number(e.target.value):item))}>{[1,2,3,4,5].map(option=><option key={option}>{option}</option>)}</select></label>)}</div></fieldset><button className="rounded-xl bg-blue-600 px-4 py-3 text-sm font-bold text-white">Save approved session</button></form>
      <form className="glass-card space-y-4 p-6" onSubmit={event=>{event.preventDefault(); void run(()=>saveProspectiveOutcome({prediction_id:Number(predictionId),outcome_observed:false,outcome_type:"No critical vital event in six-hour window",observed_at:new Date().toISOString(),adjudication_status:"single_reviewer"}),"Prospective outcome adjudicated.")}}><h2 className="text-xl font-extrabold">Prospective validation</h2><p className="text-sm text-slate-500">Adjudicate predictions only after their predefined observation window using verified source evidence.</p><label className="grid gap-1 text-sm font-bold">Pending prediction<select className={inputClass} value={predictionId} onChange={e=>setPredictionId(e.target.value)} required><option value="">Select prediction</option>{pending.map(item=><option key={String(item.prediction_id)} value={String(item.prediction_id)}>#{String(item.prediction_id)} · {String(item.model_version)} · window {String(item.window_end)}</option>)}</select></label><button className="rounded-xl bg-blue-600 px-4 py-3 text-sm font-bold text-white">Record verified negative outcome</button><p className="text-xs text-amber-700">This compact control records a negative outcome. Positive outcomes should be entered through an independently reviewed study workflow or API with supporting evidence.</p></form>
      <form className="glass-card space-y-4 p-6 xl:col-span-2" onSubmit={event=>{event.preventDefault(); const data=new FormData(event.currentTarget); void run(()=>saveEffectivenessRecord({study_code:data.get("study_code"),participant_code:data.get("participant_code"),study_arm:data.get("study_arm"),outcome_name:data.get("outcome_name"),outcome_value:Number(data.get("outcome_value")),unit:data.get("unit"),intervention_occurred:false,protocol_deviation:false}),"Effectiveness evidence saved.")}}><div className="flex items-center gap-3"><FlaskConical className="h-6 w-6 text-violet-600"/><h2 className="text-xl font-extrabold">Effectiveness-study record</h2></div><div className="grid gap-3 md:grid-cols-3"><input name="study_code" aria-label="Study code" className={inputClass} placeholder="Approved study code" required/><input name="participant_code" aria-label="Pseudonymous participant code" className={inputClass} placeholder="Participant code" required/><select name="study_arm" aria-label="Study arm" className={inputClass}><option>control</option><option>intervention</option><option>before</option><option>after</option></select><input name="outcome_name" aria-label="Outcome name" className={inputClass} placeholder="Predefined outcome" required/><input name="outcome_value" aria-label="Outcome value" type="number" step="any" className={inputClass} required/><input name="unit" aria-label="Outcome unit" className={inputClass} placeholder="Unit"/></div><button className="rounded-xl bg-violet-600 px-4 py-3 text-sm font-bold text-white">Save study record</button></form>
    </div>
    <aside className="flex gap-3 rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm text-amber-950"><ShieldCheck className="h-5 w-5 shrink-0"/><p>Regulatory preparation requires traceability, risk management and verified evidence. This workspace supports that process but cannot grant approval.</p></aside>
  </div>;
}
