from __future__ import annotations

import json
import os
from time import perf_counter
from functools import lru_cache
from pathlib import Path

import joblib
import numpy as np

from observability import component_tracker

from .features import ENGINEERED_FEATURES, vitals_to_frame


ARTIFACT_DIR = Path(os.getenv("ML_ARTIFACT_DIR", Path(__file__).resolve().parents[1] / "artifacts" / "ml"))


@lru_cache(maxsize=1)
def load_bundle():
    model_path = ARTIFACT_DIR / "model.joblib"
    report_path = ARTIFACT_DIR / "evaluation.json"
    if not model_path.exists() or not report_path.exists():
        return None
    report = json.loads(report_path.read_text(encoding="utf-8"))
    bundle = joblib.load(model_path)
    if bundle.get("schema_version") != report.get("schema_version"):
        raise RuntimeError("ML artifact and evaluation schema versions do not match")
    if not report.get("approved_for_inference", False):
        return None
    return bundle, report


def model_status() -> dict:
    loaded = load_bundle()
    if not loaded:
        return {
            "available": False,
            "reason": "No validated model artifact has been installed.",
            "artifact_directory": str(ARTIFACT_DIR),
        }
    _, report = loaded
    return {"available": True, **report}


def predict(vitals, patient_id: int) -> dict | None:
    started = perf_counter()
    loaded = load_bundle()
    if not loaded:
        return None
    bundle, report = loaded
    frame = vitals_to_frame(vitals, patient_id)
    latest = frame.iloc[[-1]][ENGINEERED_FEATURES]
    probability = float(bundle["classifier"].predict_proba(latest)[0, 1])
    threshold = float(report.get("operating_threshold", 0.5))
    anomaly_score = float(-bundle["anomaly_detector"].decision_function(latest)[0])
    shap_started = perf_counter()
    explanation = explain(bundle, latest)
    shap_ms = (perf_counter() - shap_started) * 1000
    component_tracker.increment("ml_predictions_total")
    component_tracker.set(
        ml_prediction_ms_last=round((perf_counter() - started) * 1000, 2),
        ml_shap_ms_last=round(shap_ms, 2),
    )
    return {
        "prediction_score": round(probability * 10, 2),
        "prediction_level": "High" if probability >= threshold else "Moderate" if probability >= threshold * 0.7 else "Low",
        "probability": probability,
        "anomaly_score": anomaly_score,
        "anomaly_detected": bool(bundle["anomaly_detector"].predict(latest)[0] == -1),
        "model_version": report["model_version"],
        "dataset": report["dataset"],
        "explanations": explanation,
        "drift": calculate_drift(latest, report),
        "message": "Prediction generated by the installed versioned model artifact.",
    }


def calculate_drift(latest, report: dict) -> dict:
    profile = report.get("reference_profile", {})
    scores = {}
    for feature, reference in profile.items():
        if feature not in latest or not reference or latest[feature].isna().all():
            continue
        spread = max(float(reference.get("std") or 0), 1e-6)
        scores[feature] = abs(float(latest[feature].iloc[0]) - float(reference["mean"])) / spread
    maximum = max(scores.values(), default=0.0)
    return {"score": round(maximum, 3), "feature_scores": scores, "method": "maximum reference z-score"}


def explain(bundle, latest) -> list[dict]:
    pipeline = bundle["explanation_pipeline"]
    transformed = pipeline[:-1].transform(latest)
    model = pipeline.named_steps["model"]
    try:
        import shap

        explainer = shap.Explainer(model, bundle["explanation_background"])
        values = np.asarray(explainer(transformed).values)
        if values.ndim == 3:
            values = values[:, :, 1]
        contributions = values[0]
        method = "SHAP"
    except Exception:
        raw = getattr(model, "feature_importances_", None)
        if raw is None:
            raw = getattr(model, "coef_", np.zeros((1, len(ENGINEERED_FEATURES))))[0]
        contributions = np.asarray(raw) * np.asarray(transformed[0])
        method = "model coefficient fallback"
    ranked = np.argsort(np.abs(contributions))[::-1][:8]
    return [
        {
            "feature": ENGINEERED_FEATURES[index],
            "value": float(latest.iloc[0, index]),
            "contribution": float(contributions[index]),
            "method": method,
        }
        for index in ranked
    ]
