from __future__ import annotations

import json
import os
from functools import lru_cache
from pathlib import Path

import joblib
import numpy as np

from .features import ENGINEERED_FEATURES, vitals_to_frame


ARTIFACT_DIR = Path(os.getenv("ML_ARTIFACT_DIR", Path(__file__).resolve().parents[1] / "artifacts" / "ml"))


@lru_cache(maxsize=1)
def load_bundle():
    model_path = ARTIFACT_DIR / "model.joblib"
    report_path = ARTIFACT_DIR / "evaluation.json"
    if not model_path.exists() or not report_path.exists():
        return None
    report = json.loads(report_path.read_text(encoding="utf-8"))
    bundle = joblib.load(model_path)
    if bundle.get("schema_version") != report.get("schema_version"):
        raise RuntimeError("ML artifact and evaluation schema versions do not match")
    return bundle, report


def model_status() -> dict:
    loaded = load_bundle()
    if not loaded:
        return {
            "available": False,
            "reason": "No validated model artifact has been installed.",
            "artifact_directory": str(ARTIFACT_DIR),
        }
    _, report = loaded
    return {"available": True, **report}


def predict(vitals, patient_id: int) -> dict | None:
    loaded = load_bundle()
    if not loaded:
        return None
    bundle, report = loaded
    frame = vitals_to_frame(vitals, patient_id)
    latest = frame.iloc[[-1]][ENGINEERED_FEATURES]
    probability = float(bundle["classifier"].predict_proba(latest)[0, 1])
    anomaly_score = float(-bundle["anomaly_detector"].decision_function(latest)[0])
    explanation = explain(bundle, latest)
    return {
        "prediction_score": round(probability * 10, 2),
        "prediction_level": "High" if probability >= 0.75 else "Moderate" if probability >= 0.45 else "Low",
        "confidence": round(max(probability, 1 - probability), 4),
        "probability": probability,
        "anomaly_score": anomaly_score,
        "anomaly_detected": bool(bundle["anomaly_detector"].predict(latest)[0] == -1),
        "model_version": report["model_version"],
        "dataset": report["dataset"],
        "explanations": explanation,
        "message": "Prediction generated by the installed versioned model artifact.",
    }


def explain(bundle, latest) -> list[dict]:
    pipeline = bundle["explanation_pipeline"]
    transformed = pipeline[:-1].transform(latest)
    model = pipeline.named_steps["model"]
    try:
        import shap

        explainer = shap.Explainer(model, bundle["explanation_background"])
        values = np.asarray(explainer(transformed).values)
        if values.ndim == 3:
            values = values[:, :, 1]
        contributions = values[0]
        method = "SHAP"
    except Exception:
        raw = getattr(model, "feature_importances_", None)
        if raw is None:
            raw = getattr(model, "coef_", np.zeros((1, len(ENGINEERED_FEATURES))))[0]
        contributions = np.asarray(raw) * np.asarray(transformed[0])
        method = "model coefficient fallback"
    ranked = np.argsort(np.abs(contributions))[::-1][:8]
    return [
        {
            "feature": ENGINEERED_FEATURES[index],
            "value": float(latest.iloc[0, index]),
            "contribution": float(contributions[index]),
            "method": method,
        }
        for index in ranked
    ]
